### PR TITLE
Checkout and Order page

### PR DESCRIPTION
**Pull request by AtulPant2704**
- Add Checkout page
- Display previous orders

### CODE REVIEW

**Review by starver20 — APPROVED** [review]
Checkout and order page is worling all good.

**Review by Husain01 — APPROVED** [review]
The checkout page looks good.

**Review by Sudhanshusoni45 — APPROVED** [review]
Functionality is working as intended.
One small ux issue i noticed :
- when we add items to cart, toast pops up and that is hindering the user to immediately go to the cart using top right cart btn.

**Comment by AtulPant2704** [comment]
> Functionality is working as intended. One small ux issue i noticed :
> 
> * when we add items to cart, toast pops up and that is hindering the user to immediately go to the cart using top right cart btn.

Okay will work on that. Fixed that, now toast come at bottom of the screen.

**Pull request merged**
